PROGRAM = signaltest1
OBJS    = signaltest1.o
SRCS    = $(OBJS:%.o=%.c)
CFLAGS  = -g -Wall
#CFLAGS  = -g -Wall -DIGN_SIG
#CFLAGS  = -g -Wall -DIGN_ACTION
LDFLAGS =

$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROGRAM) $(OBJS) $(LDLIBS)

